Construct renewalInfo URLs from directory+fingerprint
aarongable/draft-acme-ari pull request #2
Opened 2021-10-05 22:01 UTC by aarongable

Instead of providing renewalInfo URLs inside order objects, requiring
the ACME client to persist the URL in order to query it on a regular
basis, allow renewalInfo URLs to be constructable given only existing
client configuration (i.e. the URL of the directory) and the certificate
itself.

This allows stateless clients to not need to persist additional data,
and allows external monitoring tools to poll for renewal information
without being privy to order objects, at the cost of requiring two API
calls (one for the directory, one for the renewalInfo) each time a
client checks in.

Part of #4

2021-10-05 23:03 UTC, pgporada commented on draft-aaron-acme-ari.md
> +newNonce   | Renewal info
A client calling `/directory` should return the renewal period advertised by the CA e.g. 12h

2021-10-05 23:11 UTC, aarongable commented on draft-aaron-acme-ari.md
> +newNonce   | Renewal info
Interesting, we could include that in directory metadata. Right now, this draft has the server's suggested check-in interval instead provided by the Retry-After header on the `renewalInfo` endpoint itself.

2021-10-05 23:30 UTC, aarongable commented on draft-aaron-acme-ari.md
> +The full request URL is computed by concatenating the renewalInfo URL from the server's directory, a forward slash, and the hex-encoded SHA-1 hash of the certificate (sometimes called the certificate
I think I should instead mandate that the renewalInfo URL in the directory end with a slash.

2021-10-06 21:32 UTC, jsha requested changes

2021-10-06 21:32 UTC, jsha commented on draft-aaron-acme-ari.md
> +newNonce   | Renewal info
I think `newNonce` here should be `renewalInfo` instead, right?

```suggestion
renewalInfo   | Renewal info
```

2021-10-06 21:32 UTC, jsha commented on draft-aaron-acme-ari.md
> +The full request URL is computed by concatenating the renewalInfo URL from the server's directory, a forward slash, and the hex-encoded SHA-1 hash of the certificate (sometimes called the certificate
Let's make the standard use the same arguments (issuerKeyHash, issuerNameHash, certificateSerial). We know all CAs need a cheap way to index off of those fields, so I suspect it will be a good approach for everyone.

2021-10-06 23:19 UTC, aarongable commented on draft-aaron-acme-ari.md
> +newNonce   | Renewal info
d'oh thanks, copy-paste error.

2021-10-07 21:09 UTC, jsha approved these changes
Looks good! We should clarify a bit what we mean by hex-encoded: is lowercase acceptable?

2021-10-26 23:41 UTC, merged