Add "this has been renewed" endpoint
aarongable/draft-acme-ari pull request #22
Opened 2022-03-18 18:17 UTC by aarongable

Fixes #15

DO NOT SUBMIT until #21 has landed

2022-03-18 19:14 UTC, andygabby reviewed
Looking good! Left a few suggestions. The renewal complete endpoint would be pretty awesome if clients use it.

2022-03-18 19:14 UTC, andygabby commented on draft-aaron-acme-ari.md
> +replaced (required, boolean): Whether or not the certificate has been replaced. Clients SHOULD NOT send a request where this value is false.
I like that "Clients SHOULD NOT send a request where this value is false". Should we define that a server "MUST NOT", "SHOULD NOT" or even consider "SHOULD" change `replaced` from `true` to `false` or otherwise clarify how the server should behave if a Client asks it to set this to `false`?

2022-03-18 19:14 UTC, andygabby commented on draft-aaron-acme-ari.md
> +The server MUST verify that the request is signed by the account key of the Subscriber to which the certificate was originally issued. If the server accepts the request and the update succeeds, it re
```suggestion
The server MUST verify that the request is signed by the account key of the Subscriber to which the certificate was originally issued. If the server accepts the request and the update succeeds, it responds with an HTTP 200 status code. If the update is rejected or fails, for example because the certificate has already been marked as renewed, the server returns an error.
```

2022-03-24 00:42 UTC, jsha requested changes

2022-03-24 00:42 UTC, jsha commented on draft-aaron-acme-ari.md
> +To update the renewal status of a certificate, the client sends a POST-as-GET request to the server's `renewalInfo` URL.
```suggestion
To update the renewal status of a certificate, the client sends a POST request to the server's `renewalInfo` URL.
```

2022-03-24 00:42 UTC, jsha commented on draft-aaron-acme-ari.md
> +certID (required, string): The `CertID` of the certificate whose renewal information should be updated, in the base64url-encoded version of the DER format with trailing "=" stripped. Note: this is id
Why not POST to a URL composed with that base64url-encoded path? Possibly even the same one that was GOTten?

2022-03-24 00:42 UTC, jsha commented on draft-aaron-acme-ari.md
> +The body of the POST is a JWS object whose JSON payload contains the `CertID` of the certificate in question:
You should specify that the JWS object is authenticated to an account as defined in ACME.

2022-03-24 00:42 UTC, jsha commented on draft-aaron-acme-ari.md
> +replaced (required, boolean): Whether or not the certificate has been replaced. Clients SHOULD NOT send a request where this value is false.
Also we should define "replaced." Proposal: A certificate is considered replaced when its revocation will not affect any live services (for instance when all services using that certificate have started serving a different certificate).

We also might want to specify that it's fine to update this endpoint even if you didn't actually issue a new certificate - for instance if you don't care about the old certificate anymore because it's not in use.

2022-03-29 21:21 UTC, aarongable commented on draft-aaron-acme-ari.md
> +certID (required, string): The `CertID` of the certificate whose renewal information should be updated, in the base64url-encoded version of the DER format with trailing "=" stripped. Note: this is id
I considered that! I ended up going with this just for consistency with other existing ACME methods, particularly the revocation endpoint, which is a POST to a bare endpoint with the body containing the full cert, rather than a POST to the certificate download URL. Obviously there are reasons for that (the original certificate download URL couldn't be deterministically constructed) but I thought that consistency might be valuable? Very unsure though and happy to be convinced otherwise.

2022-03-29 22:12 UTC, aarongable commented on draft-aaron-acme-ari.md
> +The server MUST verify that the request is signed by the account key of the Subscriber to which the certificate was originally issued. If the server accepts the request and the update succeeds, it re
Thanks for noting the inconsitency of phrasing between here and line 114. I've actually changed *both* of them to unify on a happy in-between :)

2022-03-29 22:12 UTC, aarongable commented on draft-aaron-acme-ari.md
> +To update the renewal status of a certificate, the client sends a POST-as-GET request to the server's `renewalInfo` URL.
Oops, thanks!

2022-03-29 22:12 UTC, aarongable commented on draft-aaron-acme-ari.md
> +The body of the POST is a JWS object whose JSON payload contains the `CertID` of the certificate in question:
Good idea, added a reference to RFC8555 Section 6.2.

2022-03-29 22:12 UTC, aarongable commented on draft-aaron-acme-ari.md
> +replaced (required, boolean): Whether or not the certificate has been replaced. Clients SHOULD NOT send a request where this value is false.
I've updated the phrasing here to try to get at this idea.

2022-03-30 15:10 UTC, aarongable commented on draft-aaron-acme-ari.md
> +For example, to request renewal information for the end-entity certificate given in Appendix A.1, issued by the intermediate certificate given in Appendix A.2, using SHA256, the client would make the
Yeah I changed it because I didn't want to bother defining the acronym "CA" anywhere. But yeah maybe it's just obvious enough as-is.

2022-03-30 15:12 UTC, merged