Simplify request certID construction
aarongable/draft-acme-ari pull request #49
Opened 2023-08-09 22:12 UTC by aarongable

Replaces the base64url-encoded OCSP CertID with a much simpler construction: the concatenation of the certificate's AKID and its Serial. Both of these values are available from the end-entity certificate itself, without needing access to the issuer cert. Additionally, this approach doesn't require any ability to serialize ASN.1 structures, and includes algorithm agility by virtue of placing the CA in control of the algorithm used in the AKID extension.

Fixes https://github.com/aarongable/draft-acme-ari/issues/43

2023-08-09 22:42 UTC, jcjones requested changes

2023-08-09 22:42 UTC, jcjones commented on draft-ietf-acme-ari.md
> +The path component is computed by concatenating the base64url-encoding [@!RFC4648, section 5] of the bytes of the certificate's Authority Key Identifier (AKI) extension value, a literal period, and t
It's arguably clarified most by the example below, but since we generally want the text of an RFC to be unambiguous without resorting to decoding an example, but:

Reading this, I understand that the "bytes of the the certificate's Authority Key Identifier extension value" means the serialized bytes straight out of the certificate, which are defined as a `SEQUENCE` object with with tag, length, and inner values by RFC 5280. 

By that token, one could imagine the Serial Number to be the _value_ of the Serial Number, which is an ASN.1 `INTEGER` with tag, length, and an inner value. Of course, then one could argue that if the RFC meant that, it would refer to the `CertificateSerialNumber` type out of 5280. And so forth, because ambiguity.

The AKI part is pretty clear, so maybe we append _field value_ to match the AKI's wording? **"base64url-encoding of the bytes of the certificate's Serial Number field value."**

```suggestion
The path component is computed by concatenating the base64url-encoding [@!RFC4648, section 5] of the bytes of the certificate's Authority Key Identifier (AKI) extension value, a literal period, and the base64url-encoding of the bytes of the certificate's Serial Number field value. All trailing "`=`" MUST be stripped from both parts of the path component. Thus the full request url is constructed as follows, where the "`||`" operator indicates string concatenation:
```

2023-08-09 23:11 UTC, aarongable commented on draft-ietf-acme-ari.md
> +The path component is computed by concatenating the base64url-encoding [@!RFC4648, section 5] of the bytes of the certificate's Authority Key Identifier (AKI) extension value, a literal period, and t
Yep, totally agreed. I had the same thoughts about the ambiguity of specifying which bytes from the AKI to use, and liked the "field value" phrasing I landed on there. Didn't even occur to me to do the same for the Serial, but I think you're absolutely right.

2023-08-10 17:31 UTC, beautifulentropy approved these changes
Looks good to me. I've included a procedural version as an alternative. I personally find RFCs which use this format to be a bit more readable.

2023-08-10 17:31 UTC, beautifulentropy commented on draft-ietf-acme-ari.md
> +The path component is computed by concatenating the base64url-encoding [@!RFC4648, section 5] of the bytes of the certificate's Authority Key Identifier (AKI) extension value, a literal period, and t
I took a stab at a more procedure driven definition. Feel free to take or leave this:

```suggestion
To construct the path component, adhere to the following procedure:

1. Retrieve the byte representation of the leaf certificate's Authority Key Identifier (AKI) extension value. Encode this using base64url, as detailed in [@!RFC4648, section 5].
2. Similarly, retrieve and base64url encode the byte representation of the leaf certificate's Serial Number field value.
3. Strip all trailing "`=`" characters from both the encoded AKI and Serial Number values.
4. Concatenate the two encoded values using a period (`.`) separator.

The resulting request URL is assembled by appending this path component to the `renewalInfo URL`:

~~~ text
   request_url = {renewalInfo URL} || '/' || base64url(AKI) || '.' || base64url(Serial)
~~~

Definitions:
- `{renewalInfo URL}`: The base URL of the renewalInfo endpoint.
- `base64url(AKI)`: The base64url encoded AKI value, with all trailing "`=`" characters stripped.
- `base64url(Serial)`: The base64url encoded Serial Number, with all trailing "`=`" characters stripped.

Note: Within the expression above, "||" symbolizes string concatenation.
```

2023-08-10 18:48 UTC, aarongable commented on draft-ietf-acme-ari.md
> +The path component is computed by concatenating the base64url-encoding [@!RFC4648, section 5] of the bytes of the certificate's Authority Key Identifier (AKI) extension value, a literal period, and t
I fear that this construction-based style is _too_ prescriptive -- what if the client gets the serial from elsewhere (e.g. it's own persistent state file, rather than the cert itself)? I think I've hit the best of both worlds by leaving the normative text mostly the same, but making the example much more procedural like this.

2023-08-10 18:52 UTC, merged